steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lastminute-ai-api:$SHORT_SHA", "./backend"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/lastminute-ai-api:$SHORT_SHA"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - lastminute-ai-api
      - --image
      - gcr.io/$PROJECT_ID/lastminute-ai-api:$SHORT_SHA
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
images:
  - gcr.io/$PROJECT_ID/lastminute-ai-api:$SHORT_SHA
substitutions:
  _REGION: us-central1
